[package]
edition = "2021"
name = "not-so-fast-derive"
version = "0.1.0"

[lib]
proc-macro = true

[dependencies]
once_cell = "1"
proc-macro2 = "1"
quote = "1"
syn = { version = "1", features = ["parsing", "extra-traits"] }
